console.log("Custom js file loaded");window.onscroll=function(){scrollFunction();};function scrollFunction(){var topbarHeight=document.getElementById("wrapper-topbar")?document.getElementById("wrapper-topbar").offsetHeight:0;if(document.body.scrollTop>topbarHeight||document.documentElement.scrollTop>topbarHeight){document.getElementById("navb").classList.add("bg-white");document.getElementById("navb").classList.remove("bg-transparent");document.getElementById("navb").classList.add("navbar-shadow");document.getElementById("navb").classList.add("active");}else{document.getElementById("navb").classList.remove("bg-white");document.getElementById("navb").classList.add("bg-transparent");document.getElementById("navb").classList.remove("navbar-shadow");document.getElementById("navb").classList.remove("active");}}
window.onscroll=function(){scrollFunction();};document.addEventListener('DOMContentLoaded',function(){const navbarToggler=document.querySelector('.navbar');navbarToggler.addEventListener('click',function(){document.body.classList.toggle('menu-open');});});var scrolled=false;document.addEventListener("DOMContentLoaded",function(){var topbarHeight=document.getElementById("wrapper-topbar")?document.getElementById("wrapper-topbar").offsetHeight:0;var scrolled=false;var logo=document.getElementById('logo');var src=logo.getAttribute('src');var originalLogoIsBlack=src.includes('black');window.addEventListener('scroll',function(){if(originalLogoIsBlack)return;var currentSrc=logo.getAttribute('src');if(!scrolled&&window.pageYOffset>topbarHeight){scrolled=true;if(!currentSrc.includes('black')){logo.setAttribute('src',currentSrc.replace('white','black'));}}
else if(scrolled&&window.pageYOffset<=topbarHeight){scrolled=false;if(currentSrc.includes('black')){logo.setAttribute('src',currentSrc.replace('black','white'));}}});});if(window.matchMedia('(min-width: 992px)').matches){var dropdowns=document.querySelectorAll('.dropdown');dropdowns.forEach(function(dropdown){dropdown.addEventListener('mouseenter',function(){this.querySelector('.dropdown-menu').classList.add('show');this.querySelector('.dropdown-toggle').classList.add('show');});dropdown.addEventListener('mouseleave',function(){this.querySelector('.dropdown-menu').classList.remove('show');this.querySelector('.dropdown-toggle').classList.remove('show');});});}
window.addEventListener('load',function(){var carouselItems=document.getElementsByClassName('carousel-item');var maxHeight=0;for(var i=0;i<carouselItems.length;i++){if(carouselItems[i].clientHeight>maxHeight){maxHeight=carouselItems[i].clientHeight;}}
for(var i=0;i<carouselItems.length;i++){carouselItems[i].style.height=maxHeight+'px';}});var root=document.documentElement;const lists=document.querySelectorAll('.switch-module-offer');lists.forEach(el=>{const listItems=el.querySelectorAll('li');const n=el.children.length;el.style.setProperty('--total',n);});document.addEventListener("DOMContentLoaded",function(){var switches=document.querySelectorAll("[id^='switch-price-']");switches.forEach(function(switchElement){switchElement.addEventListener("change",function(){var displaySwitchElements=document.querySelectorAll(".display-switch");displaySwitchElements.forEach(function(switchElem){if(switchElement.checked){switchElem.classList.remove("fade-out");switchElem.classList.add("fade-in");}else{switchElem.classList.remove("fade-in");switchElem.classList.add("fade-out");}});var monthlyElements=document.querySelectorAll(".display-switch-monthly");var yearlyElements=document.querySelectorAll(".display-switch-yearly");monthlyElements.forEach(function(monthlyElement){if(switchElement.checked){monthlyElement.classList.remove("fade-out");monthlyElement.classList.add("fade-in");}else{monthlyElement.classList.remove("fade-in");monthlyElement.classList.add("fade-out");}});yearlyElements.forEach(function(yearlyElement){if(switchElement.checked){yearlyElement.classList.remove("fade-in");yearlyElement.classList.add("fade-out");}else{yearlyElement.classList.remove("fade-out");yearlyElement.classList.add("fade-in");}});});switchElement.dispatchEvent(new Event("change"));});});function setCookie(name,value,days){var expires="";if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));expires="; expires="+date.toUTCString();}
document.cookie=name+"="+(value||"")+expires+"; path=/";}
function isCookieSet(cookieName){var encodedCookieName=encodeURIComponent(cookieName)+"=";var cookieArray=document.cookie.split(';');for(var i=0;i<cookieArray.length;i++){var cookie=cookieArray[i].trim();if(cookie.indexOf(encodedCookieName)==0){return true;}}
return false;}
document.addEventListener('DOMContentLoaded',function(){var closeButton=document.getElementById('close-wrapper-topbar');var navElement=document.getElementById('navb');if(!isCookieSet('close-wrapper-topbar')){var wrapperTopbar=document.querySelector('#wrapper-topbar');if(wrapperTopbar){wrapperTopbar.style.display='block';}}
if(closeButton){closeButton.addEventListener('click',function(){setCookie('close-wrapper-topbar','hidden',1);var wrapperTopbar=document.querySelector('#wrapper-topbar');if(wrapperTopbar){wrapperTopbar.remove();}
navElement.style.top="0";navElement.style.position="fixed";});}
if(isCookieSet('close-wrapper-topbar')){var wrapperTopbar=document.querySelector('#wrapper-topbar');if(wrapperTopbar){wrapperTopbar.remove();}}});document.addEventListener("DOMContentLoaded",function(){var navElement=document.getElementById("navb");function getTopbarHeight(){var topbar=document.getElementById("wrapper-topbar");return topbar?topbar.offsetHeight:0;}
var topbarHeight=getTopbarHeight();if(navElement){navElement.style.top=topbarHeight+"px";navElement.style.position="absolute";window.addEventListener("scroll",function(){topbarHeight=getTopbarHeight();if(window.scrollY>=topbarHeight){navElement.style.top="0";navElement.style.position="fixed";}else{navElement.style.top=topbarHeight+"px";navElement.style.position="absolute";}});}});document.addEventListener('DOMContentLoaded',function(){var switches=document.querySelectorAll('[id^="switch-price-"]');function updateAllLabels(){switches.forEach(function(switchElem){var container=switchElem.closest('.form-check');var monthlyLabel=container.querySelector('.form-check-monthly');var yearlyLabel=container.querySelector('.form-check-yearly');if(switchElem.checked){yearlyLabel.classList.add('fw-semibold');monthlyLabel.classList.remove('fw-semibold');}else{monthlyLabel.classList.add('fw-semibold');yearlyLabel.classList.remove('fw-semibold');}});}
switches.forEach(function(switchElem){switchElem.addEventListener('change',updateAllLabels);});updateAllLabels();});